### ISSUE TITLE
Clicking a _blank URL to open an external window does nothing

### ISSUE THREAD

**Issue by evevision** [evevision/evevision#30]
Opening links doesn't work unless it routes the entire window itself. Any sort of external link opening is broken entirely. It may be opening in the background.

**Comment by wereii** [comment]
This seems like a problem I have encountered in different electron app. [Caprine](https://github.com/sindresorhus/caprine/issues/1189#issuecomment-609765491)

Basically by default Electron has it's own rules when opening a new window, if I may say it tries to act like a real program spawning new windows instead of being a browser.

In Caprine I solved it by using [`nativeWindowOpen:`](https://www.electronjs.org/docs/api/window-open#using-chromes-windowopen-implementation).

**Comment by jaydoobs** [comment]
Resolved in 1.7.0
