### ISSUE TITLE
Why is the accessToken sent to api.eve.vision?

### ISSUE THREAD

**Issue by modmynitro** [evevision/evevision#64]
https://github.com/evevision/evevision/blob/0320db32da5e3b154aac8126537a706a5c9d6b12/app/main/api/client.ts#L261-L268

**Comment by jaydoobs** [comment]
It's some old beta code that hasn't been used since the very first (semi-private) beta, we were testing the stability of the websockets API which was authorized using your access token. If you check elsewhere you'll see the client class isn't actually used.

**Comment by modmynitro** [comment]
Wouldn't it be better to remove the code?

**Comment by jaydoobs** [comment]
It will be used again in the future, although it will be changed in quite a number of ways. It's left around as an example for me to refer to later.

**Comment by hditano** [comment]
Why do not remove it for later usage? There's a few people talking about it on /r/eve and on the forums..

**Comment by jaydoobs** [comment]
Because it's unused, unreferenced code that I don't feel like hunting down in old commits when I want to look at how I did it before just to satisfy the tinfoil hattery of a few people that likely aren't going to use EveVision anyways. There will be a similar client in the near future that reimplements this anyways, as there will be a remote ESI proxy that plugins will optionally have to go through to do certain multi-character things securely.

It doesn't even end up in the final JS bundle that is distributed to users.

I haven't seen more than a couple people say anything about it either.
